plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'spec/fixtures/**/*'
# style
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/WordArray:
  EnforcedStyle: percent
Style/HashSyntax:
  EnforcedStyle: ruby19

# Layout
Layout/LineLength:
  Enabled: true
  Max: 120
Layout/IndentationStyle:
  EnforcedStyle: spaces
Layout/IndentationWidth:
  Width: 2

# Rspec
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true