plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'spec/fixtures/**/*'

# style
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
Style/WordArray:
  EnforcedStyle: percent
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/Documentation:
  Enabled: false

# Layout
Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
Layout/IndentationStyle:
  EnforcedStyle: spaces
Layout/IndentationWidth:
  Width: 2
Layout/TrailingWhitespace:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

# Metrics
Metrics/BlockLength: 
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 15

# budler
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Rspec
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 5
RSpec/ExampleLength:
  Max: 15
RSpec/NestedGroups:
  Max: 5
RSpec/ContextWording:
  Enabled: false

# Rails
Rails/SkipsModelValidations:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false